### ISSUE TITLE
Compatibility with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by jhoffmcd** [sambernard/react-preload#11]
I wanted to use transitions on the `loadingIndicator`, but nothing seems to work.

Should this work with `ReactCSSTransitionGroup`?

**Comment by sambernard** [comment]
@jhoffmcd can you show me an example of what you are trying to do?

**Comment by jhoffmcd** [comment]
@sambernard I don't have the piece of code anymore, but I think it may be my implementation. I think it should work with `ReactCSSTransitionGroup`. If I had to try again I think I could get it to work.
