### ISSUE TITLE
crossorigin breaks cache when using it without it

### ISSUE THREAD

**Issue by jrmyio** [sambernard/react-preload#16]
I was trying to use the ImageHelper and ImageCache to preload some background images I am using in my CSS. However, as of :
https://github.com/sambernard/react-preload/commit/5c80e8f319999f1c771407036e4f6aa66a315c2f

it seems to break (tested in Chrome) from using the cached image in a CSS background image.

I think this crossorigin setting should be made optional.

**Comment by sambernard** [comment]
@ConneXNL I actually just saw this on one of my sites last week, will update shortly.
