### ISSUE TITLE
Images failed to preload

### ISSUE THREAD

**Issue by obykoo** [sambernard/react-preload#17]
I am always getting images failed to preload. What am I doing wrong?

```
let images=[
            "/assets/images/1.png",
            "/assets/images/2.png",
            "/assets/images/3.png",
            "/assets/images/4.png"
        ]
 let loadSpan= <span className="loadspan">
                              <i className="spin fa fa-refresh"/>
                          </span>
<Preload
                loadingIndicator={loadSpan}
                images={images}
                autoResolveDelay={10000}
                resolveOnError={true}
                mountChildren={true}
            >
...other select component
</Preload>
```

When looking at network activity they are loaded sucessfully, but library still spams console..

**Comment by obykoo** [comment]
I also tried with full path and looked into network activity , they are fetch sucessfully from server with 200 OK , but I am still getting spammed in console with "Images failed to preload"

**Comment by urbantumbleweed** [comment]
👍

**Comment by sambernard** [comment]
@obykoo can you put together a codepen for me to look at?

**Comment by obykoo** [comment]
Hello, I put together this codepen:
[https://codepen.io/anon/pen/dvvwML?editors=1111](https://codepen.io/anon/pen/dvvwML?editors=1111)
There is no warning in console with codepen.

However when I try same code on my localhost , there is warning...

```
import React from 'react';
import Preload from 'react-preload';
import Select from 'react-select';

export default class App extends React.Component {

    render() {
        let images=["http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/5_kr6t52.png",
            "http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/4_wg4sg4.png",
            "http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/3_rl1hdy.png"];

        let optionsRender=[];
        optionsRender.push({value:"1",label: <span className="option"><img src="http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/5_kr6t52.png"></img>{"1"}</span> });
        optionsRender.push({value:"2",label: <span className="option"><img src="http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/4_wg4sg4.png"></img>{"2"}</span> });
        optionsRender.push({value:"3",label: <span className="option"><img src="http://res.cloudinary.com/dt4katy80/image/upload/v1489174402/3_rl1hdy.png"></img>{"3"}</span> });

        let loadSpan= <span className="loadspan">
                              <i className="spin fa fa-refresh"/>
                          </span>;

        return (<div>  <Preload
            loadingIndicator={loadSpan}
            images={images}
            autoResolveDelay={15000}
            resolveOnError={true}
            mountChildren={true}
        >
            <Select
                options={optionsRender}
                autosize={true}
                className={"Select"}
                clearable={false}
                searchable={false}
                autoload={true}
            />
        </Preload>

        </div>);
    }

}
```
```
ReactDOM.render(
      <App />
       ,
    document.getElementById('app')
);
```

Is there any way I can at least turn off console.warn?

**Comment by sambernard** [comment]
No- there's not an option to remove the warning. When accessing it locally are you using a domain (eg http://localhost), or just viewing a file directly in your browser?

**Comment by obykoo** [comment]
When using localy while developing I am acessing them by domain name. Anyway this is not problem because code I posted above giving me same warning and images there are hosted externally as you can see.

**Comment by sambernard** [comment]
I'm actually not seeing the warning when I look. What browser are you using?

**Comment by Mesoptier** [comment]
I've been receiving the same warning, even though the Network inspector shows all images to load correctly (status 200).

The warning gets thrown in the `_handleSuccess` method ([modules/Preload.js#L82](https://github.com/sambernard/react-preload/blob/master/modules/Preload.js#L82)). I guess the assumption was made that `this.autoResolveTimeout` would only be set if the timeout had completed, which of course is not the case. This means that the warning will _always_ get thrown if you have the `autoResolveDelay` prop set.

This can be easily fixed by moving the warning and call to `_handleSuccess` into a separate callback ([modules/Preload.js#L67](https://github.com/sambernard/react-preload/blob/master/modules/Preload.js#L67)). Like this:

```javascript
this.autoResolveTimeout = setTimeout(() => {
    console.warn('images failed to preload, auto resolving');
    this._handleSuccess();
}, this.props.autoResolveDelay);
```

**Comment by sambernard** [comment]
This has been resolved: https://github.com/sambernard/react-preload/commit/99c953bed322d1453b177ca2856464aa37925fb4#diff-44a458d379c4c083b784f6b5b953a210L89
