### ISSUE TITLE
Using a fake image throws an error in the console but onError is not called

### ISSUE THREAD

**Issue by jrmyio** [sambernard/react-preload#25]
I am using a preload on a non-existing image.

I get the error in the console:
`ImageHelper.js:67 failed to preload images/test.pxz`

However, the onError is not called whereas onSuccess is. I have resolveOnError also turned off.

This is happening since 5.1, 5.0 was fine.

**Comment by sambernard** [comment]
This is fixed in https://github.com/sambernard/react-preload/commit/62f9a08f509546234de0c91033fec75cc39cfac4 and will be in the next release.
