### ISSUE TITLE
TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by Slyke** [sambernard/react-preload#29]
Getting:
```
/node_modules/react-preload/lib/Preload.js:27
children: _react.PropTypes.element.isRequired,
TypeError: Cannot read property 'element' of undefined
```

With Code:

```
const loadingIndicator = (<div>Loading...</div>)
const imagesL = [
  'img1.png',
  'img2.png',
  'img3.png'
]
<Preload
loadingIndicator={loadingIndicator}
images={imagesL}
autoResolveDelay={5000}
mountChildren={true}
resolveOnError={true}
>
  {<div>Hi</div>}
</Preload>
```

**Comment by Gsiete** [comment]
It seems to be an issue with newer versions of React:
https://reactjs.org/docs/typechecking-with-proptypes.html
(see the note)
It was fixed in: https://github.com/sambernard/react-preload/pull/23
But not merged...

**Comment by nuclearspike** [comment]
+1.

**Comment by remeddy** [comment]
+1

**Comment by hiradyazdan** [comment]
+1 can this be merged please?

**Comment by lucasconstantino** [comment]
@sambernard do you still maintain this project? If not so, I would recommend providing access to others ;)

**Comment by Jlevett** [comment]
can you please merge the fix.

**Comment by sambernard** [comment]
Fixed, and new version has been published
