### ISSUE TITLE
Preload is undefined

### ISSUE THREAD

**Issue by jb-san** [sambernard/react-preload#4]
Hi, I was trying to use this in a project, but I use es6 so the var `Preload = require("react-preload");`
becomes `import Preload from "react-preload"`

but Preload is undefined and I can not render the component, any ideas ?

**Comment by sambernard** [comment]
Hey- can you try using `import {Preload} from "react-preload"` and see if that works?

**Comment by blzzz** [comment]
Doesn't seam to work in ES6. Any news about that issue?

**Comment by sambernard** [comment]
I should have a fix in today.

**Comment by sambernard** [comment]
@blzzz Can you try installing the latest version from npm?

**Comment by blzzz** [comment]
Works perfectly, thanks a lot.
